# создаить категорию у пользователя

POST http://localhost:8080/category
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZGZzZnNkZmtvcG91aSIsImlhdCI6MTY4OTAwMzQ4NywiZXhwIjoxNjg5MDg5ODg3fQ.syphUsUE-hTReqGjk56Wopw_VJhNaSqDW5b4iDL_BG0
Content-Type: application/json

{
  "name": "category20"
}

###
# получать категории у пользователя
GET http://localhost:8080/category/all
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzZGZzZnNkZmtvcG91aSIsImlhdCI6MTY4OTAwNDAwNCwiZXhwIjoxNjg5MDkwNDA0fQ.--2AQ7iDdHjCL_-6HAwuaCbD7Sxmq0XveAZ2wDYN0bU
Accept: application/json

###

